import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { cn } from "@/lib/utils";

const iransansFont = localFont({
  src: [
    {
      path: "../public/fonts/IRANSansXThin.ttf",
      weight: "100",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansXUltraLight.ttf",
      weight: "200",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansXLight.ttf",
      weight: "300",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansXRegular.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansXMedium.ttf",
      weight: "500",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansXDemiBold.ttf",
      weight: "600",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansXBold.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansXExtraBold.ttf",
      weight: "800",
      style: "normal"
    },
    {
      path: "../public/fonts/IRANSansXBlack.ttf",
      weight: "900",
      style: "normal"
    },
  ],
  variable: '--font-iransans'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={cn('min-h-screen bg-dark-300 font-sans antialiased', iransansFont.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
        >
          {children}
        </ThemeProvider>
        <Toaster position="bottom-center" />
      </body>
    </html>
  );
}
